//
//  BbqMenuItem.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

class BbqMenuItem: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _restaurantId: String?
    var _id: String?
    
    class func dynamoDBTableName() -> String {

        return "share-mobilehub-1774715290-bbq_menu_item"
    }
    
    class func hashKeyAttribute() -> String {

        return "_restaurantId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_id"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_restaurantId" : "restaurant_id",
               "_id" : "id",
        ]
    }
}
