//
//  Locations.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

class Locations: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    @IBOutlet var id: String!
    @IBOutlet var comment: String!
    @IBOutlet var x: NSNumber!
    @IBOutlet var y: NSNumber!
    @IBOutlet var z: NSNumber!
    
    class func dynamoDBTableName() -> String {
        
        return "share-mobilehub-1774715290-locations"
    }
    
    class func hashKeyAttribute() -> String {
        
        return "id"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
            "id" : "id",
            "comment" : "comment",
            "x" : "x",
            "y" : "y",
            "z" : "z",
        ]
    }
}

