//
//  Locations.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

class Locations: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _id: String?
    var _comment: String?
    var _lat: String?
    var _long: String?
    var _x: NSNumber?
    var _y: NSNumber?
    var _z: NSNumber?
    
    class func dynamoDBTableName() -> String {
        
        return "share-mobilehub-1774715290-locations"
    }
    
    class func hashKeyAttribute() -> String {
        
        return "_id"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
            "_id" : "id",
            "_comment" : "comment",
            "_lat" : "lat",
            "_long" : "long",
            "_x" : "x",
            "_y" : "y",
            "_z" : "z",
        ]
    }
}
