//
//  Locations.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

class Locations: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var id: String?
    var comment: String?
    var lat: String?
    var long: String?
    var x: String?
    var y: String?
    var z: String?
    var time: String?
    
    class func dynamoDBTableName() -> String {
        
        return "share-mobilehub-1774715290-locations"
    }
    
    class func hashKeyAttribute() -> String {
        
        return "id"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
            "id" : "id",
            "comment" : "comment",
            "lat" : "lat",
            "long" : "long",
            "time" : "time",
            "x" : "x",
            "y" : "y",
            "z" : "z",
        ]
    }
}
